/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import View.Paineis.TransicaoPaineis;
import View.Paineis.painel_consulta;
import View.Paineis.painel_entrada;
import View.Paineis.painel_saida;

/**
 *
 * @author chelsea
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Index() {
        initComponents();
        
        new TransicaoPaineis(jPanel2, new painel_consulta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra_vertical = new javax.swing.JPanel();
        btn_menu_sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        btn_entrada = new javax.swing.JButton();
        btn_saida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 410));
        setUndecorated(true);
        setSize(new java.awt.Dimension(400, 410));

        barra_vertical.setBackground(new java.awt.Color(38, 75, 101));

        btn_menu_sair.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu_sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_menu_sair.setForeground(new java.awt.Color(38, 75, 101));
        btn_menu_sair.setText("SAIR");
        btn_menu_sair.setBorder(null);
        btn_menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_sair.setFocusPainted(false);
        btn_menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu_sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu_sairMouseExited(evt);
            }
        });
        btn_menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_sairActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/logo100.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btn_consultar.setBackground(new java.awt.Color(38, 75, 101));
        btn_consultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setText("HOME");
        btn_consultar.setBorder(null);
        btn_consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consultar.setFocusPainted(false);
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_consultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_consultarMouseExited(evt);
            }
        });
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_entrada.setBackground(new java.awt.Color(38, 75, 101));
        btn_entrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_entrada.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrada.setText("ENTRADA");
        btn_entrada.setBorder(null);
        btn_entrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrada.setFocusPainted(false);
        btn_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_entradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_entradaMouseExited(evt);
            }
        });
        btn_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entradaActionPerformed(evt);
            }
        });

        btn_saida.setBackground(new java.awt.Color(38, 75, 101));
        btn_saida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_saida.setForeground(new java.awt.Color(255, 255, 255));
        btn_saida.setText("SAIDA");
        btn_saida.setBorder(null);
        btn_saida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_saida.setFocusPainted(false);
        btn_saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saidaMouseExited(evt);
            }
        });
        btn_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barra_verticalLayout = new javax.swing.GroupLayout(barra_vertical);
        barra_vertical.setLayout(barra_verticalLayout);
        barra_verticalLayout.setHorizontalGroup(
            barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_verticalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barra_verticalLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(btn_menu_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btn_consultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barra_verticalLayout.setVerticalGroup(
            barra_verticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra_verticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(btn_menu_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barra_vertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra_vertical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_menu_sairActionPerformed

    private void btn_menu_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_sairMouseEntered

    }//GEN-LAST:event_btn_menu_sairMouseEntered

    private void btn_menu_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu_sairMouseExited

    }//GEN-LAST:event_btn_menu_sairMouseExited

    private void btn_consultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseEntered

    }//GEN-LAST:event_btn_consultarMouseEntered

    private void btn_consultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseExited

    }//GEN-LAST:event_btn_consultarMouseExited

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        new TransicaoPaineis(jPanel2, new painel_consulta());
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entradaMouseEntered

    }//GEN-LAST:event_btn_entradaMouseEntered

    private void btn_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entradaMouseExited

    }//GEN-LAST:event_btn_entradaMouseExited

    private void btn_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entradaActionPerformed
        btn_consultar.setBackground(new Color(38,75,101));
        btn_consultar.setForeground(new Color(255,255,255));
        
        btn_entrada.setBackground(new Color(255,255,255));
        btn_entrada.setForeground(new Color(38,75,101));
        
        btn_saida.setBackground(new Color(38,75,101));
        btn_saida.setForeground(new Color(255,255,255));
        new TransicaoPaineis(jPanel2, new painel_entrada());
    }//GEN-LAST:event_btn_entradaActionPerformed

    private void btn_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entradaMouseClicked
        
    }//GEN-LAST:event_btn_entradaMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        btn_consultar.setBackground(new Color(255,255,255));
        btn_consultar.setForeground(new Color(38,75,101));
        
        btn_entrada.setBackground(new Color(38,75,101));
        btn_entrada.setForeground(new Color(255,255,255));
        
        btn_saida.setBackground(new Color(38,75,101));
        btn_saida.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saidaActionPerformed
        btn_consultar.setBackground(new Color(38,75,101));
        btn_consultar.setForeground(new Color(255,255,255));

        btn_entrada.setBackground(new Color(38,75,101));
        btn_entrada.setForeground(new Color(255,255,255));

        btn_saida.setBackground(new Color(255,255,255));
        btn_saida.setForeground(new Color(38,75,101));
        new TransicaoPaineis(jPanel2, new painel_saida());
    }//GEN-LAST:event_btn_saidaActionPerformed

    private void btn_saidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saidaMouseExited

    }//GEN-LAST:event_btn_saidaMouseExited

    private void btn_saidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saidaMouseEntered

    }//GEN-LAST:event_btn_saidaMouseEntered

    private void btn_saidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saidaMouseClicked

    }//GEN-LAST:event_btn_saidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_vertical;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_entrada;
    private javax.swing.JButton btn_menu_sair;
    private javax.swing.JButton btn_saida;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
