/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Paineis;

import Controller.Carregar_buscar_tabela;
import Controller.Remover;
import Model.Estadia;
import java.awt.Color;
import java.awt.Font;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chelsea
 */
public class painel_consulta extends javax.swing.JPanel {

    /**
     * Creates new form painel_consulta
     */
    public painel_consulta() {
        initComponents();
        
        tabela_consulta.getTableHeader().setFont(new Font("Arial", Font.BOLD, 11));
        tabela_consulta.getTableHeader().setOpaque(false);
        tabela_consulta.getTableHeader().setBackground(new Color(38,75,101));
        tabela_consulta.getTableHeader().setForeground(new Color(255,255,255));
        tabela_consulta.setRowHeight(25);
        
        carregar_tabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_consulta = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_x = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        c_ticket = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tabela_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nº Ticket", "Nome cliente", "Cpf", "Placa", "Data entrada", "Hora entrada", "Data saida", "Hora saida", "Valor"
            }
        ));
        tabela_consulta.setToolTipText("");
        tabela_consulta.setEnabled(false);
        tabela_consulta.setFocusable(false);
        tabela_consulta.setGridColor(new java.awt.Color(235, 235, 235));
        tabela_consulta.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabela_consulta.setRowHeight(25);
        tabela_consulta.setSelectionBackground(new java.awt.Color(239, 239, 239));
        tabela_consulta.setShowVerticalLines(false);
        tabela_consulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela_consulta);

        btn_buscar.setBackground(new java.awt.Color(38, 75, 101));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("BUSCAR");
        btn_buscar.setFocusPainted(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME");
        jLabel1.setToolTipText("");

        btn_x.setBackground(new java.awt.Color(255, 255, 255));
        btn_x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_x.setForeground(new java.awt.Color(102, 102, 102));
        btn_x.setText("X");
        btn_x.setBorder(null);
        btn_x.setBorderPainted(false);
        btn_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });

        btn_deletar.setBackground(new java.awt.Color(154, 42, 42));
        btn_deletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_deletar.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletar.setText("DELETAR REGISTRO");
        btn_deletar.setFocusPainted(false);
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        c_ticket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        c_ticket.setForeground(new java.awt.Color(173, 173, 173));
        c_ticket.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(235, 235, 235), new java.awt.Color(255, 255, 255)));
        c_ticket.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_ticketFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_ticketFocusLost(evt);
            }
        });
        c_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ticketActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Nº Ticket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_ticket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_deletar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void carregar_tabela(){
        Carregar_buscar_tabela tb = new Carregar_buscar_tabela();
        List<Estadia> l2 = tb.Carregar_tabela();
        
        DefaultTableModel modelo = (DefaultTableModel) tabela_consulta.getModel();
        modelo.setNumRows(0);
       
        for(Estadia l: l2){
            modelo.addRow(new Object[]{
                l.getTicket(),
                l.getNome_cliente(),
                l.getCpf_cliente().substring(0,3)+"."+l.getCpf_cliente().substring(3,6)+"."+l.getCpf_cliente().substring(6,9)+"-"+l.getCpf_cliente().substring(9,11),
                l.getPlaca_veiculo(),
                l.getData_entrada(),
                l.getHora_entrada(),
                l.getData_saida(),
                l.getHora_saida(),
                l.getValor()
            });
        }
    }
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try{
            Carregar_buscar_tabela tb = new Carregar_buscar_tabela();
            Estadia l = tb.Buscar(c_ticket.getText());
            DefaultTableModel modelo = (DefaultTableModel) tabela_consulta.getModel();
            modelo.setNumRows(0);
            modelo.addRow(new Object[]{
                l.getTicket(),
                l.getNome_cliente(),
                l.getCpf_cliente().substring(0,3)+"."+l.getCpf_cliente().substring(3,6)+"."+l.getCpf_cliente().substring(6,9)+"-"+l.getCpf_cliente().substring(9,11),
                l.getPlaca_veiculo(),
                l.getData_entrada(),
                l.getHora_entrada(),
                l.getData_saida(),
                l.getHora_saida(),
                l.getValor()
            });
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Valor procurado nao encontrado");
        }
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_xActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        Remover r = new Remover();
        r.Remover(parseInt(c_ticket.getText()));
        carregar_tabela();
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void c_ticketFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_ticketFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ticketFocusGained

    private void c_ticketFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_ticketFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ticketFocusLost

    private void c_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ticketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_x;
    private javax.swing.JTextField c_ticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_consulta;
    // End of variables declaration//GEN-END:variables
}
